language: java
jdk:
  - oraclejdk8
services:
  - postgresql
before_script:
  - psql -c "CREATE USER pal WITH SUPERUSER PASSWORD 'secreto';" -U postgres
  - psql -c "CREATE DATABASE secret_pal_test WITH OWNER pal;" -U postgres

script: 
  - mvn -Dmaven.javadoc.skip=true test -Dspring.profiles.active=ci

