language: java
jdk:
  - oraclejdk8

script: 
  - "cd secretPal-backend"
  - mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -Dcobertura.skip=true -B -V
  - mvn clean cobertura:check -B -V

