version: '3'

services:
  db:
    image: postgres:10
    restart: always
    ports:
      - 5432:5432
    environment:
      - 'POSTGRES_USER=pal'
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db: